/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */

package POG.interfaceGraphique.fenetre;

import java.util.Vector;

public class FenetreVerification extends FenetrePOG {

  public FenetreVerification(FenetrePrincipale fp){
    super(fp);
  }


  public void montrerResultat(Vector vectBadFile , Vector vectBadElmtsPresentation) {
    this.setVisible(true);
  }


  public void actionOK() {

    this.setVisible(false);

  }



  public void actionAnnuler() {

    this.setVisible(false);

  }

}
