/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */
package POG.interfaceGraphique.fenetre.PanneauxDetails;
import java.awt.Component;
import java.awt.Rectangle;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

import POG.interfaceGraphique.action.ControleurPanneaux;
import POG.interfaceGraphique.fenetre.FenetrePrincipale;
import POG.objetMetier.ElementPresentation;
import POG.objetMetier.Guide;

public class PanneauGuide extends PanneauDetail {
  private JScrollPane jScrollPane1;
  private JLabel type = new JLabel();

  public PanneauGuide(ControleurPanneaux control) {
    super(control);
    try {
      jbInit();
    }
    catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void jbInit() throws Exception {
    btnajouterguide.setVisible(false);
    jScrollPane1 = new JScrollPane();
    jScrollPane1.setBounds(new Rectangle(11, 265, 250, 64));
    jScrollPane1.setBorder(
        BorderFactory.createCompoundBorder(
        BorderFactory.createCompoundBorder(
        BorderFactory.createTitledBorder("Type du guide"),
        BorderFactory.createEmptyBorder(5, 5, 5, 5)),
        jScrollPane1.getBorder()));

    type.setBounds(new Rectangle(26, 275, 240, 54));

    this.add(type);
    this.add(jScrollPane1, null);
  }

  public void afficherMenuGuides(Component compo, int x, int y) {
  }

  public void loadElement(ElementPresentation elem) {
    _elementCourant = elem;
    setNom_Pres(elem.get_nomPresentation());
    setLabelNomPres(FenetrePrincipale.INSTANCE.getLnkLangues().valeurDe("nomGuide"));
    setDesc(elem.get_description());
    setIcon(elem.get_icone());
    if (elem.getContenu() != null)
      setFichier_associe(elem.getContenu().getFile());
    else
      setFichier_associe(null);
    setIcon(elem.get_icone());
    type.setText(((Guide)elem).getType());
    this.updateUI();

  }

 /* public void setList_type(String[] list) {

    list_type = new JComboBox(list);
    jScrollPane1.setViewportView(list_type);
  }*/
}

