/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */



package POG.application.sauvegarde;



import java.io.OutputStreamWriter;

public abstract interface Sauvegarde {

  public abstract void sauver(OutputStreamWriter out, boolean FlagExporter);


// ajout d'un 3eme parametre \uFFFD charger, pour la classe Presentation
  public abstract void charger(String cle, String valeur);

}

