/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/*
 * DialogueBox.java
 *
 * Created on 12 avril 2002, 10:53
 */

package POG.outil.html.pika;

import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author  Administrateur
 */
public class DialogueBox extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    /** A return status code - returned if Non button has been pressed */
    public static final int RET_NON = 2;

    /** Creates new form DialogueBox */
    public DialogueBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel();
        ouiButton = new javax.swing.JButton();
        nonButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        TextPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Enregistrer ?");
        setModal(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        ouiButton.setMnemonic(KeyEvent.VK_O);
        ouiButton.setText("Oui");
        ouiButton.setNextFocusableComponent(nonButton);
        ouiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiButtonActionPerformed(evt);
            }
        });

        ouiButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ouiButtonKeyPressed(evt);
            }
        });

        buttonPanel.add(ouiButton);

        nonButton.setMnemonic(KeyEvent.VK_N);
        nonButton.setText("Non");
        nonButton.setNextFocusableComponent(cancelButton);
        nonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonButtonActionPerformed(evt);
            }
        });

        nonButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nonButtonKeyPressed(evt);
            }
        });

        buttonPanel.add(nonButton);

        cancelButton.setMnemonic(KeyEvent.VK_C);
        cancelButton.setText("Cancel");
        cancelButton.setNextFocusableComponent(ouiButton);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        cancelButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelButtonKeyPressed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        TextPanel.setLayout(new java.awt.GridLayout(2, 1, 0, 4));

        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setText("Voulez-vous enregistrer");
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        TextPanel.add(jLabel2);

        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setText("le document en cours ?");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14));
        TextPanel.add(jLabel3);

        getContentPane().add(TextPanel, java.awt.BorderLayout.CENTER);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(350, 140));
        setLocation((screenSize.width-350)/2,(screenSize.height-140)/2);
    }//GEN-END:initComponents

    private void ouiButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ouiButtonKeyPressed
        // Add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            doClose(RET_OK);
        }
    }//GEN-LAST:event_ouiButtonKeyPressed

    private void nonButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nonButtonKeyPressed
        // Add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            doClose(RET_NON);
        }
    }//GEN-LAST:event_nonButtonKeyPressed

    private void cancelButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelButtonKeyPressed
        // Add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            doClose(RET_CANCEL);
        }
    }//GEN-LAST:event_cancelButtonKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // Add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE)
        {
            doClose(RET_CANCEL);
        }
    }//GEN-LAST:event_formKeyPressed

    private void nonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonButtonActionPerformed
        // Add your handling code here:
        doClose(RET_NON);
    }//GEN-LAST:event_nonButtonActionPerformed

    private void ouiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_ouiButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
    }

    private javax.swing.JButton ouiButton;
    private javax.swing.JButton nonButton;
    private javax.swing.JButton cancelButton;

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private JPanel buttonPanel;
    private javax.swing.JPanel TextPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
