/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */

package POG.objetMetier;

import java.io.File;
import java.net.URL;

/**
 * @stereotype entity
 */

public class Contenu {
  private File _file;
  private String _pathBiblio;

  public Contenu(File fich, String pathB) {
    _pathBiblio = pathB;
    _file = fich;
  }

  public String toString() {
    return this._file.getName();
  }

  public URL get_url() {
    try {
      return _file.toURL();
    }
    catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  public File getFile() {
    return _file;
  }

  public String getAbsolutePath() {
    return _file.getAbsolutePath();
  }

  public String get_uri() {
    return _file.getName();
  }

  public String getRelativeToBiblioPath() {
    String abso = getAbsolutePath();
    if (!abso.startsWith(_pathBiblio))
      return abso;
    String relat = abso.substring(_pathBiblio.length() + 1);
    return relat;
  }

  public void setFile(File file) {
    this._file = file ;
  }
}
