/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */



package POG.objetMetier;

import java.util.Vector;

import javax.swing.ImageIcon;

import org.ipsquad.apes.model.extension.SpemDiagram;
import org.ipsquad.apes.model.spem.core.ModelElement;

import POG.interfaceGraphique.utile.trace.Debug;


public class PresentationElementModele extends ElementPresentation {



  private boolean _modifiable;
  private String _stringType;

  /**
   * @supplierCardinality 1
   * @directed
   */
  private ModelElement lnkModelElement;
//  private ProcessComponent lnkProcessComponent;

  /** @directed
   * @supplierCardinality 0..**/
  private Vector lnkGuide1;

  /**

   * @supplierCardinality 1

   * @directed

   */

  public void setModelElement(ModelElement el)
  {
    this.lnkModelElement = el;
  }

  public ModelElement getLnkModelElement() {
    return lnkModelElement;
  }


  public PresentationElementModele(String id, ImageIcon ico, ModelElement element) {
    super(id, ico);
    lnkModelElement = element;
    this.lnkGuide = new Vector();
    _modifiable = true;
    if (element == null)
      return;
    this._nomPresentation = element.getName();
    if (element instanceof SpemDiagram)
        _modifiable = false;

  }

  public boolean estValide(Debug lnkDebug){
    //les diagrammes d'activit\uFFFDs ne snt pas \uFFFD prednre en compte
    if (this.lnkModelElement instanceof SpemDiagram) {
      return true;
    }

    // Quel verif ???
    return true;
  }

  public boolean is_modifiable() {
    return _modifiable;
  }

  public String getIdentificateurExterne() {
//    if (lnkProcessComponent == null)
      return Integer.toString(lnkModelElement.getID());
/*    else
      return Integer.toString(lnkProcessComponent.getID());*/
  }


}

