	/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */



package POG.objetMetier;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.Vector;

import javax.swing.ImageIcon;

import org.ipsquad.apes.model.extension.SpemDiagram;
import org.ipsquad.apes.model.spem.core.ModelElement;
import org.ipsquad.apes.model.spem.process.structure.WorkProduct;

import POG.interfaceGraphique.fenetre.FenetrePrincipale;
import POG.interfaceGraphique.utile.trace.Debug;
import POG.utile.PogToolkit;


public class PresentationElementModele extends ElementPresentation {



  private boolean _modifiable;
  private String _typeProduit = "";
  private String _nominmodel;
  private String _placearbre;

  /**
   * @supplierCardinality 1
   * @directed
   */
  private ModelElement lnkModelElement;
//  private ProcessComponent lnkProcessComponent;

  /** @directed
   * @supplierCardinality 0..**/
  private Vector lnkGuide1;

  /**

   * @supplierCardinality 1

   * @directed

   */

	private void askChangeNom() {
		String quest = FenetrePrincipale.INSTANCE.getLnkLangues().valeurDe("questouinonchangernommodele");
		quest = quest.replaceFirst("ARG0", _nomPresentation);
		quest = quest.replaceFirst("ARG1", _nominmodel);
		if (PogToolkit.askYesNoQuestion(quest, false, FenetrePrincipale.INSTANCE) == PogToolkit._YES)
			_nomPresentation = _nominmodel;		
	}

  public void setModelElement(ModelElement el)
  {
  	_nominmodel = el.getName();
  	if (!lnkModelElement.getName().equals(el.getName())) {
		askChangeNom();
    }
	this.lnkModelElement = el;
  }

  public ModelElement getLnkModelElement() {
    return lnkModelElement;
  }

  public PresentationElementModele(String id, ImageIcon ico, ModelElement element) {
    super(id, ico);
    lnkModelElement = element;
    this.lnkGuide = new Vector();
    _modifiable = true;
    if (element == null)
      return;
    this._nomPresentation = element.getName();
    if (element instanceof SpemDiagram)
        _modifiable = false;
	_nominmodel = element.getName();
	_placearbre = id;
  }

  public boolean estValide(Debug lnkDebug){
    //les diagrammes d'activit\uFFFDs ne snt pas \uFFFD prednre en compte
    if (this.lnkModelElement instanceof SpemDiagram) {
      return true;
    }

    // Quel verif ???
    return true;
  }

  public boolean is_modifiable() {
    return _modifiable;
  }

  public String getIdentificateurExterne() {
//    if (lnkProcessComponent == null)
      return Integer.toString(lnkModelElement.getID());
/*    else
      return Integer.toString(lnkProcessComponent.getID());*/
  }
	
	public String get_nominmodel() {
		return _nominmodel;
	}
	public String get_placearbre() {
		return _placearbre;
	}

	public void set_nominmodel(String nominmodel) {
		if (_nominmodel.equals(nominmodel) || nominmodel.equals(""))
			return;
		askChangeNom();
	}
	
	public void set_placearbre(String _placearbre) {
		this._placearbre = _placearbre;
	}

	public String get_typeProduit() {
		return _typeProduit;
	}
	
	public void set_typeProduit(String produit) {
		if (lnkModelElement instanceof WorkProduct)
			_typeProduit = produit;
	}
	public void sauver(OutputStreamWriter out, boolean FlagExporter) {
		super.sauver(out, FlagExporter);
		try {
			out.write("<typeproduit>");
			out.write(_typeProduit);
			out.write("</typeproduit>\n");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
}

