/*
 * POG
 * Copyright (C) 2004 Team POG
  *
 * This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


/* Generated by Together */
package POG.interfaceGraphique.utile.menu;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.filechooser.FileFilter;

import POG.utile.MyMultiFileFilter;
import POG.utile.PogToolkit;

public class MenuListener implements ActionListener {

  POGMenu pgm;

  public MenuListener(POGMenu p) {
    pgm = p;
  }


 public void actionPerformed(ActionEvent evt) {

   if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Ouvrir"))) {
     MyMultiFileFilter fd = new MyMultiFileFilter(".pog");
     fd.addExt(".pre");
     File pres = PogToolkit.chooseFileWithFilter(pgm.lnkFenetrePrincipale, fd);
     if (pres == null || !(pres.getName().endsWith(".pog") || pres.getName().endsWith(".pre")))
     {
       if (pres == null)
       {
         return;
       }
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Vous ne pouvez ouvrir ce type de fichier");
       return;
     }

     pgm.lnkFenetrePrincipale.getLnkSysteme().ouvrirPresentation(pres.toString());
//     pgm.lnkFenetrePrincipale.getLnkArbrePresentation().selectionnerRacine();
   }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Enregistrer"))){
     if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() != null){
       if (this.pgm.lnkFenetrePrincipale.get_pathSave().equalsIgnoreCase(""))
         this.pgm.lnkFenetrePrincipale.getLnkFenetreEnregistrerSous().setVisible(true);
       else
         pgm.lnkFenetrePrincipale.getLnkSysteme().enregistrerPresentation();
     }
     else
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Presentation vide");
   }else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("enregistrersous"))){
     if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() !=null)
       pgm.lnkFenetrePrincipale.getLnkFenetreEnregistrerSous().setVisible(true);
     else
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Presentation vide");
   } else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("apes")))   {
     String argvApes = new String("");
     if ((this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() != null)
         && (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().get_pathModele() != null))
       argvApes = this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().get_pathModele().getPath();
     try {
       String str = pgm.lnkFenetrePrincipale.getLnkSysteme().getLnkPreferences().getPathApes();
       System.out.println("java -jar " + str + " " +argvApes);
       Runtime.getRuntime().exec("java -jar " + str + " " +argvApes);
     }
     catch (Exception e) {
       e.printStackTrace();
     }
   }//*/
/*   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("ExporterIEPP")))
     Exporter.versIepp(pgm.lnkFenetrePrincipale.getLnkSysteme().getLnkControleurExporter(),pgm.lnkFenetrePrincipale.getLnkDebug());*/
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Quitter")))
     pgm.lnkFenetrePrincipale.getLnkSysteme().quitter();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Preferences")))
     pgm.lnkFenetrePrincipale.afficherFenetrePreferences();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("viderlog")))
     pgm.lnkFenetrePrincipale.getLnkDebug().clearTexte();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Exporter")))
   {
     if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() !=null)
     {
       if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation().lnkProcessComponent == null
          || this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation().lnkProcessComponent.getValidate() != 0
          || PogToolkit.askYesNoQuestion(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("apesmodelenonvaliderquestioncontinuer"), false, this.pgm.lnkFenetrePrincipale) == PogToolkit._YES)
       {
         pgm.lnkFenetrePrincipale.getLnkFenetreExport().setVisible(true);
       }
     }
     else
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Presentation vide");
   }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("EditeurHTML")))
     pgm.lnkFenetrePrincipale.getLnkappliTest().lancement();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Nouveau")))
     pgm.lnkFenetrePrincipale.getLnkFenetreOuverture().setVisible(true);
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("SansModele"))){
     pgm.lnkFenetrePrincipale.getLnkFenetreOuverture().setVisible(true);
   }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("AvecModele"))) {
     pgm.lnkFenetrePrincipale.getLnkFenetreNouvellePresentationAvecModele().setVisible(true);
   }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("apropos")))
      pgm.lnkFenetrePrincipale.getLnkFenetreAPropos().setVisible(true);
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("AjouterElementPresentation")))
     pgm.lnkFenetrePrincipale.getLnkSysteme().ajouterElementPre();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("Synchroniser")))
   {
     if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() !=null)
       pgm.lnkFenetrePrincipale.getLnkArbreExplorateur().load();
     else
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Presentation vide");
   }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("syncapes")))
     {
       if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().get_pathModele() == null)
       {
         this.pgm.lnkFenetrePrincipale.getLnkDebug().afficher("Votre presentation n'est pas liee a un modele : synchronisation impossible");
       }
       else {
         pgm.lnkFenetrePrincipale.getLnkSysteme().synchroniserApes();
       }
     }
  else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("VerifierCoherence")))
  {
    if (this.pgm.lnkFenetrePrincipale.getLnkSysteme().getlnkControleurPresentation().getlnkPresentation() != null)
      pgm.lnkFenetrePrincipale.getLnkSysteme().verifiePresentation();
    else
       pgm.lnkFenetrePrincipale.getLnkDebug().debogage("Presentation vide");
  }
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("ManuelUtilisation")))
     POG.utile.HtmlViewer.mymain();
   else if (evt.getActionCommand().equals(pgm.lnkFenetrePrincipale.getLnkLangues().valeurDe("extraire")))
     pgm.lnkFenetrePrincipale.getLnkSysteme().extraireIcone();
   else
     pgm.lnkFenetrePrincipale.getLnkDebug().afficher(evt.getActionCommand() + " : Non pris en compte...");


 }

 private class MyFileFilter extends FileFilter{
   private String _ext = null;
   public MyFileFilter(String ext){
     super();
     _ext = ext;
   }

   public boolean accept(File fich){
     if (fich.isDirectory())
       return true;
     else
       return fich.getName().endsWith(_ext);
   }
   public String getDescription(){
       return _ext;
   }
 }

}